### PR TITLE
Merge pull request #2 from AC-2015-Sem2/master

### PR DESCRIPTION
**Pull request by Alecs94**
.

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
Why do you have all the files from everyone in this commit?

**Comment by Alecs94** [comment]
I don't know, I just wanted to make a git sync. I'm sorry for that.
Pe 23.05.2015 23:49, "Cosma Alex" notifications@github.com a scris:

**Comment by Alex-Cosma** [comment]
Ok, don't worry about it, it's fine, but I can't merge your request. does it contain the homework for next week?
if not, what exactly did you try to accomplish?

**Comment by Alecs94** [comment]
No, I just wanted to give a pull request to my repository, like I always
do, to synchronize it with the main one, honestly. But if you want, you can
delete it.

**Comment by Alex-Cosma** [comment]
it's quite alright, I do not think you can sync your repository with the big one with a pull request.
Nevertheless, we'll 'fix' everything at the lab, just remind me about this, ok?

**Pull request closed without merging**
