### PR TITLE
Homework.

### PR DESCRIPTION
**Pull request by AlexandruGH**
Greetings!
I have a bug that is a little triky to solve for me.
At compile I have 0 errors and 0 warnings,but when I run the program it crashes.
I run with the debugger and I receive a SIGSEGV segmentation fault at my first function.
I should allocate dynamically the sentinel pointer?

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
Unless magic exists and is in the favour of programmers, yes

**Comment by AlexandruGH** [comment]
Finally it works!

**Comment by Alex-Cosma** [comment]
GG

**Comment by AlexandruGH** [comment]
Greetings!
I have 2 problems:
1)When I make a pull request it also appears on my files the old version of homework on a red background.This makes it a little hard to notice if I pull the right homework.
2)In the second problem from homework, my code has 0 errors and 0 warnings but it crashes at runing .I run the program with the debugger and I receive a SIGSEGV segmentation fault on the 55 line of code after the while loop was once passed.

**Comment by Alex-Cosma** [comment]
1) the red part is only the deleted lines
2) line 55 of which file?

**Comment by AlexandruGH** [comment]
I make some changes.It works now.

**Pull request merged**
