### PR TITLE
this is my first commit!

### PR DESCRIPTION
**Pull request by Ranapop**
This is my first version of the first assignment.

### CODE REVIEW

**Comment by Ranapop** [comment]
I changed the first assignment.

**Comment by Ranapop** [comment]
About the extra assignment: I know I haven't exactly waited for your approval to send the extra assignment but as it is the last day I just couldn't help myself from sending it. I hope it's alright.
P.S. I know i have a lot of strange names throughout the code files, it's mainly due to the fact that i worked on it in several different days and I sometimes lost continuity. Sorry about that.

**Comment by Alex-Cosma** [comment]
You don't have to have my approval to send anything ^^ 
You only need to have finished the first assignment (which you did)

**Comment by Ranapop** [comment]
Thank you :). I'm really glad to have such a positive response. I'll try even harder next time!

**Pull request merged**
