### PR TITLE
Homework new.

### PR DESCRIPTION
**Pull request by AlexandruGH**
Finally I solved the problem.

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
I presume it works now?

**Comment by AlexandruGH** [comment]
Yes it works.

**Comment by AlexandruGH** [comment]
Greetings!
I have a problem with github.I'm trying to upload my new homework in my own repository but after I deleted all the files that were there and I put the new ones, I tried to commit ,but didn't see all my new files there .So I can't push them.

**Comment by Alex-Cosma** [comment]
Are you sure you checked all the files when commiting?

**Pull request merged**
