### PR TITLE
extra assignment4

### PR DESCRIPTION
**Pull request by DariLupea**
extra assignment 4

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
This works great as well!
- could have been made slightly more modular though

**Comment by DariLupea** [comment]
Alex, ai punctat doar functiile care faceau ce trebuie? Restul codului care
nu era total corect nu l-ai punctat?

**Comment by Alex-Cosma** [comment]
Da, așa am punctat la toată lumea. Erau funcții scurte, dar dacă crezi că am uitat ceva, mă pot uita deseară din nou peste lucrarea ta - dacă tot a fost pe stick.

**Comment by DariLupea** [comment]
Pai atunci nu stiu daca mai are rost...  Pentru 2 dintre ele am scris
codul, din punctul meu de vedere era ok, dar nu faceau ce trebuie. So, this
is it.

2015-04-08 19:03 GMT+03:00 Cosma Alex notifications@github.com:

**Comment by Alex-Cosma** [comment]
Don't worry/be upset. I'm sure you'll do better on the next one. Keep up the good work!

**Comment by DariLupea** [comment]
Hope so! Thank you!

Trimis de pe Samsung Mobile

-------- Mesaj original --------
De la: Cosma Alex notifications@github.com 
Date: 08.04.2015  22:24  (GMT+02:00) 
Către: AC-2015-Sem2/DSA-lab DSA-lab@noreply.github.com 
Cc: DariLupea dari.lupea@gmail.com 
Subiect: Re: [DSA-lab] extra assignment4 (#206) 

Don't worry/be upset. I'm sure you'll do better on the next one. Keep up the good work!

**Pull request merged**
