### PR TITLE
Assignment 7 - Chaining

### PR DESCRIPTION
**Pull request by FejerAlpar**

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
You forgot about the table from the assignment. 
But, I'm sure you'll be able to fill it up, your code looks good.

**Comment by FejerAlpar** [comment]
Thank's. I didn't actually read the assignment, just opened the skeleton and wrote the code for the functions, and heard about the additional hash functions....I'll pay attention next time. Btw I believe the reason for the merge sort having less comparisons for the "worst" case is that the first sub-array is longer than the second if the nr. of elements is odd. (in case of 7 elements 4 and 3), so when the first sub-array contains the smaller elements (best case), there will be 4 comparisons, but in the "worst" case, there will be only 3 .

**Comment by Alex-Cosma** [comment]
I just tested your theory by starting with an odd number of elements (10001) and then an even number of elements (10000) in the initial array.
The results stayed the same. Hopefully I understood what you said - if not, tell me.

**Comment by Alex-Cosma** [comment]
But I took a pen and paper and got exactly what you actually meant. 
You are perfectly right. Because the array was split with more elements on the LEFT side, you had more comparisons on the "best" case than in the worst case as more elements had to be compared until we could be sure that we can put everything from the 'untouched' array directly in the resulting array.

Thank you for this, and good job thinking about it

**Pull request merged**
