### PR TITLE
Assignment 4

### PR DESCRIPTION
**Pull request by andras13**
Could you check if it is good or not? It works but there might be some efectiveness problems or others...

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
Pretty please, put the "input.txt" file here as well

**Comment by andras13** [comment]
But I did not use the input file in this program. I read the data from keyboard.

**Comment by Alex-Cosma** [comment]
Weird, I have no idea what I was looking at last night - nevermind, I'll look over it later today

**Comment by andras13** [comment]
And I also did not call the delete function. I was(and am) in a hurry :(

**Comment by Alex-Cosma** [comment]
This is not really ok, I checked it with the input sequence `1 2 3 4 5` and it gave me a very unbalanced tree. (sorry for the late answer..)

**Comment by andras13** [comment]
Yes, but I don't know why. I was searching already the problem, but didn't find yet. If you have some advices I would be grateful.

**Comment by Alex-Cosma** [comment]
http://www.geeksforgeeks.org/avl-tree-set-1-insertion/ check this out

**Pull request merged**
