### PR TITLE
This is my first version of assignment 6.1

### PR DESCRIPTION
**Pull request by Ranapop**

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
Your union function should have looked something like:

```

int uni(int * parent, int i,int j)
{
    if(i!=j)
    {
        parent[j]=i;
        return 1;
    }
    return 0;
}
```

and then called like:

```
u=getParent(parent, minEdge.source);
v=getParent(parent, minEdge.destination);
if(uni(parent, u, v))
    {
       minCost+=minEdge.weight;
       edges[nrEdgesAdded++] = minEdge;
    }
```

**Comment by Alex-Cosma** [comment]
But the rest is ok

**Comment by Ranapop** [comment]
I see. Should I update the code? :?

**Comment by Alex-Cosma** [comment]
It's not necessary, no

**Pull request merged**
