### PR TITLE
Assignment6 ✔

### PR DESCRIPTION
**Pull request by BologaMarius**
Hope it's ok!?

### CODE REVIEW

**Comment by BologaMarius** [comment]
I have used the functions uni and getParent, as you asked..Hope is better than previous version!?

**Comment by BologaMarius** [comment]
If not, let me know!

**Comment by Alex-Cosma** [comment]
Yes, it's better - next time, please update the same project and don't create a different one!

**Comment by BologaMarius** [comment]
Yes, Sir!

**Pull request merged**
