### PR TITLE
HTHW

### PR DESCRIPTION
**Pull request by ioansx**
I've found on the net a nice hash function that gives a good distribution in chaining and relatively few collisions in open addressing. I hope the open addressing program doesn't crash, I had some problems with it, but solved most (maybe all)  of them.

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
Looking at your chaining distributions, I would say that the hash function which you found is not that great. Don't forget to compute the standard deviation as mentioned in the assignment requirements. What value do you get for that?

**Comment by Alex-Cosma** [comment]
Very good job code-wise, you did everything very well, but I would suggest looking over a few more hash functions and try it out with them. Try searching for specific `hash functions on strings`.

**Comment by Alex-Cosma** [comment]
And also, don't forget to fill the tables from the assignment folder and put them in your folder.

Good work nevertheless

**Comment by ioansx** [comment]
I'm sorry I sent the assignment half-done, I forgot to read the actual .docx files.
I really tried to find a better function and also tested some famous ones, but they seem to be no better than the first "nice function". Actually they give almost the same results.

**Comment by Alex-Cosma** [comment]
Good! It does not matter at all. Your implementation looks good and the fact that those hash functions behave relatively the same is a result in its own.

Well done

**Comment by Alex-Cosma** [comment]
Awesome job this semester. One of the best over-achievers!

**Pull request merged**
