### PR TITLE
Assignment 7

### PR DESCRIPTION
**Pull request by LacraDanciu**
First of all, I created my own functions for hashing (2 and 3). I don't know if I should have done that.. They are random, but I liked the way they work considering collisions.
Second of all, I don't know if chaining is good (I think is wrong... -> I told you I can't understand hash tables, especially chaining.) I have a program for hash tables, with chaining (a search engine :+1: ) but isn't quite this problem so I can't apply here what I've done there. 
I also had to modify your functions for lists because they gave me errors. 
Third, I can't figure out how to do standard deviation. I am also very stressed with another project, so this might be one of the reasons.
I will stop now :)) ^^

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
Also, try out your open addressing with `_50000` and it crashes

**Comment by Alex-Cosma** [comment]
I don't mind having "invented" hash functions as long as they behave well

**Comment by LacraDanciu** [comment]
my hash functions are crashing on _50000. Honestly, I am way too tired to try again. I don't know why I find chaining harder than open addressing.

**Comment by Alex-Cosma** [comment]
Chaining in a nutshell:

consider your hash table

```
[
-
-
-
-
-
-
-
]
```

7 initially empty (represented by a dash) buckets. Indexes range from 0-6.

Consider the following elements are to be inserted with the format `Value(hash)`
`A(3), B(2), C(1), D(1), E(1), F(2), G(5), H(2), I(2).`

At the end, after inserting everything the hash table will look like:

```
[
-
C -> D -> E
B -> F -> H -> I
A
-
G ->
-
]
```

Notice, elements that are in the same bucket have the same `hash`. Because they are the have the exact same hash value, you're not trying to find a different position for them, no. You are linking them together in a list.

**Pull request merged**
