### PR TITLE
Assignment 4

### PR DESCRIPTION
**Pull request by gergo-papp**

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
Crashes on start

**Comment by gergo-papp** [comment]
On my Laptop it works all right. I will check it when I get home

**Comment by gergo-papp** [comment]
I have absolutely no idea why it doesn't run. Could you help me?
The program runs perfectly inside CodeBlocks, both in debugging and compile/run cases. It crashes if I open the .exe file in the bin folder.

**Comment by Alex-Cosma** [comment]
It's strange that it actually works in debug mode for me as well. nevertheless, I tested it out in debug mode and it works just fine, so it's :+1:

**Pull request merged**
