### PR TITLE
Hash Tables

### PR DESCRIPTION
**Pull request by andreipop95**
Here's my work. Please tell me how can I improve it. Thank you

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
In the Open Addressing table I think you switched the two values .. there can't be so many resizes and so few collisions

**Comment by Alex-Cosma** [comment]
good work

**Comment by andreipop95** [comment]
What values did I switch in the Open Addressing table ?

**Comment by Alex-Cosma** [comment]
Columns with resize / max collisions

**Pull request merged**
