### PR TITLE
Assignment_HashTables

### PR DESCRIPTION
**Pull request by vladms**

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
I think you switched the values in `Instructions-7.docx`. So many resizes and so few collisions?
Also, those tables have to be filled!!

**Comment by Alex-Cosma** [comment]
Your chaining program always shows 0.00% filled on all buckets

**Comment by vladms** [comment]
I will resend the Chaining part ..I found the error.
I am lost with tables

**Comment by Alex-Cosma** [comment]
For some reason, your code only works in debug mode. Usually this means that there are some allocation problems somewhere. However, the distribution on each bucket now works

**Pull request merged**
