### PR TITLE
Assignment 3

### PR DESCRIPTION
**Pull request by andreipop95**

### CODE REVIEW

**Comment by andreipop95** [comment]
Would you please evaluate my code?

**Comment by Alex-Cosma** [comment]
Patience, young padawan..

**Comment by Alex-Cosma** [comment]
Also, if you could be so kind as to upload all the project files, including the `.cbp` one, that'd be great.

**Comment by andreipop95** [comment]
I'm sorry for not being patient. I taught you skipped my code. I have modified the sources. Is my code any better now ?

**Comment by Alex-Cosma** [comment]
Yup

**Comment by andreipop95** [comment]
Ok. Thank you

**Pull request merged**
