### PR TITLE
Assignment 6 adv. algs

### PR DESCRIPTION
**Pull request by alexh95**

### CODE REVIEW

**Comment by alexh95** [comment]
I followed the pseudo-code form the wiki to make bellman ford, for kruskal I made an equivalent algorithm: instead of building some set logic, I just used a vector for connected component tree tagging.

**Comment by Alex-Cosma** [comment]
```
   // Step 3: check for negative-weight cycles
   for each edge (u, v) with weight w in edges:
       if distance[u] + w < distance[v]:
           error "Graph contains a negative-weight cycle"
   return distance[], predecessor[]
```

It's quite alright, but just print out whenever you have a negative cycle

**Comment by alexh95** [comment]
Also about 6.2 I was thinking about splitting the graph in n-paritie parts and the figuring out what can I exclude.

**Comment by Alex-Cosma** [comment]
I think you should read on `vertex cover approximation algorithms` first. There is at least one which is very simple and efficient

**Comment by alexh95** [comment]
I implemented an algorithm that gives a somewhat good soultion.

**Comment by alexh95** [comment]
I added that arbNumber parameter since it would output the whole set of vertices if it picked the first edge it encountered every time.

**Comment by Alex-Cosma** [comment]
well yes, of course, for complete graphs the optimal solution is trivial.
How does it behave for non-complete graphs?

**Comment by alexh95** [comment]
The result is a set smaller than the total number of vertices, depending on how the edges are chosen(the chose arbitrary edge part). i.e. prints 10/10 vertices if it chooses edges in lexicographical order and 8/10 edges if it always skips the first 2 valid edges ad picks the 3rd. So there is a bit of random involved.

**Comment by Alex-Cosma** [comment]
I need a maximum upper bound and reason why we have that maximum upper bound.

**Comment by Alex-Cosma** [comment]
At each step, your `arbNumber` should take a different arbitrary value!

**Comment by Alex-Cosma** [comment]
For the vertex cover I would recommend the following:
- create a list or array which will initially contain all the edges
- generate a random number from 0 to size(list)-1
- add the chosen edge to your final edge-list
- remove any other edges from your list which are adjacent to any of the two vertexes which were part of your chosen list.

(hint: the list / array part is OPTIONAL. simply choose a way to `randomly` select an edge!)

Why this? Well there is no real random factor in your implementation and that makes it rather ..boring. 
Once you implement this in a random fashion, try out an experiment. Create a more complex graph and run your program a few times on it. Try to see how often you reach a close to optimal or close to "edge" (2 times worse) solution.
Write these values down for let's say.. 20-30 runs (you can even export them directly from your program) and then plot a graph in excel. What's the given distribution? is it normal? (btw, you'll have to compute the optimal solution yourself or using an optimal vertex cover solution)
Try changing the graph after this and do the test again. Does this influence the underlying distribution?
Again, randomness is key in this case.

**Pull request merged**
