### PR TITLE
My 4-th homework

### PR DESCRIPTION
**Pull request by mariababan**
I took the example tree from lab 3...hope is it ok

### CODE REVIEW

**Comment by mariababan** [comment]
I have also added the extra part :)

**Comment by mariababan** [comment]
Yep I see. But I can't identify where is the problem...hmmm

**Comment by Alex-Cosma** [comment]
Good job on making it modular!
- the delete function however still needs work

**Comment by mariababan** [comment]
I know. Can you give me a hint? I can't identify why that is happening...

**Pull request merged**
