### PR TITLE
Homework+Extra Assignment

### PR DESCRIPTION
**Pull request by AlexandruGH**
My code doesn't print the good solution.In the example input ,after running ,the node 15 is discarded.

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
Your insert function isn't working well - try checking out what's wrong

**Comment by AlexandruGH** [comment]
I made some modifications and it works now.

**Comment by Alex-Cosma** [comment]
Why in the world did I merge this!? huh.
Could you please create a new pull request with your modifications? Apparently I decided to merge this some day yesterday..

**Comment by AlexandruGH** [comment]
Here is the extra assignment as well.

**Comment by Alex-Cosma** [comment]
I tested your code with

```
    int i=20;
    for(i=20;i<180;i++)
        root = insertNode(root, i);
    for(i=25;i<175;i++)
        root = deleteNode(root, i);
```

insertion works great.
deletion, not so much. I'm giving you half the points

**Pull request merged**
