### PR TITLE
My homework. I hope it's okay.

### PR DESCRIPTION
**Pull request by Alecs94**

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
Your _.depend_ has not changed at all that means that you didn't even compile it.

**Comment by Alecs94** [comment]
I compiled it several times. I don't know what's wrong but it is not
because of that.
Pe 06.05.2015 19:51, "Cosma Alex" notifications@github.com a scris:

**Comment by Alecs94** [comment]
I have the .depend in the folder, along with my whole project. I don't know
why it didn't go with all of it.
Pe 06.05.2015 20:54, "Alexandru Muresan" amury94@gmail.com a scris:

**Comment by Alex-Cosma** [comment]
Fair enough..

**Pull request merged**
