### PR TITLE
First version of 5.1 assignment

### PR DESCRIPTION
**Pull request by andras13**

### CODE REVIEW

**Comment by andras13** [comment]
I hope it is ok now.

**Comment by Alex-Cosma** [comment]
So, very interesting way of thinking about it and solving it with that `-1` that marks the end of a nodes neighbours. Another way of doing it would be to have an array of lists, and then each element in the array would be a list. That way, `adjList[0]` would be a `first` in a list of `0's` neighbours etc.

Now, what you should do is try implementing dfs and bfs's "get all neighbours" functions using this new list and that's it.

**Comment by andras13** [comment]
So I made the "getNumberOfNeighborsOfVertex1" and "getAllNeighborsOfVertex1" functions which counts the neighbor stuffs using the list. Now. The BFS and DfsRecurs uses the "getNumberOfNeighborsOfVertex" and "getAllNeighborsOfVertex" functions the DFS "getNumberOfNeighborsOfVertex1" and "getAllNeighborsOfVertex1" just to compare their working. I also saw how to solve with -adjList[0]-.

**Comment by Alex-Cosma** [comment]
Good!

**Pull request merged**
