### PR TITLE
assignment6.1

### PR DESCRIPTION
**Pull request by CorinaAlb**
I didn't respect the exact structure from the skeleton, but the algorithms seem to work fine. I've also attached a new txt file for the oriented graph in the Bellman-Ford algorithm.

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
Your Bellman Ford implementation is correct. 
Could you however please briefly explain your Kruskal implementation? I'm just curious if I correctly understood what you did there.

**Comment by CorinaAlb** [comment]
I've considered the algorithm ends when it finds    nrOfVertices-1    edges that fulfill either the condition that at least one of the vertices is UNVISITED (retained in that vector mst that takes the value VISITED or UNVISITED) or, if both vertices have already been visited, I compute the matrix of the roads using the Roy-Floyd algorithm to see if there already exists a path between the two vertices. If the answer is yes, than the value of the matrix adjacencyMATRIX at the address [e.source][e.destination] is 1 and the program assigns the maximum value MAX at that address [e.source][e.destination], so it can move on. If the answer is no, than the value of the matrix adjacencyMATRIX at the address [e.source][e.destination] is 0 and it counts another edge.

**Comment by Alex-Cosma** [comment]
I'm not exactly sure where you are applying Roy-Floyd (which is actually Floyd-Warshall from what I've read) in your Kruskal implementation. Which lines exactly?

**Comment by CorinaAlb** [comment]
Sorry I've mistaken the names of the codes. Floyd-Warshall is supposed to begin at line 82, where I've (incorrectly )written '  //Roy-Floyd  ' at the end of the line . It is the function 
int *_createAdjacencyMatrix(int *_MATRIX)

**Comment by CorinaAlb** [comment]
and that line 82 is in source graphAlgorithms.c

**Comment by Alex-Cosma** [comment]
Ok, I get it now. However, the problem is, with this implementation, you have to first make sure that you run Floyd Warshall on your graph. That's a huge "minus"! And in some real-life cases, it could be unacceptable.
I would like you to rethink and re-implement this part of your algorithm using the basic Kruskal approach

**Comment by CorinaAlb** [comment]
Sorry I've added the assignment so many times in a row, I'm mainly a day dreamer and I don't realize what I'm doing :))

**Comment by Alex-Cosma** [comment]
There we go, yes! This is good.

**Comment by CorinaAlb** [comment]
hey, Hi! I looked in the notes table and I saw that I have the mark 1 for assignments 4 and 5.I thought this was possible only if I didn't sent you the homework. I know assignment 5 didn't work right, and I sent it to you late, but about assignment 4,  it worked just fine along with the extra assignment. I know you're busy but will you please take some time to check again the assignment 4 I've sent you? I know you're received it because you commented on it. 

Have a great night !

**Comment by Alex-Cosma** [comment]
Hey,

Thank you for pointing this out to me, you are perfectly right. Assignment 4 slipped through my fingers somehow - I updated the grades .xls and added your grade + the extra points.

However, for assignment 5, I still can't get it to compile - maybe check it out and fix it?

**Comment by CorinaAlb** [comment]
yes, I am going to fix it . Thank you!

**Pull request merged**
