### PR TITLE
Assignment 4 is here!

### PR DESCRIPTION
**Pull request by alexh95**
Is there a better solution for the rotation function?

### CODE REVIEW

**Comment by alexh95** [comment]
So far I'm not sure if I need to rotate multiple times per insertion(I only rotated once). For large trees the prettyPrint didn't look too balanced but checking the left and right max depths for every node and using isBST confirm it is a complete binary search tree.

**Comment by alexh95** [comment]
I fixed the rotation code which was throwing nodes into the void.
Basically , when doing the zig-zag to zig-zig a child was getting neglected and kept getting lost:
"aux->right = NULL" instead of "aux->right = root->left->left" etc.

**Comment by alexh95** [comment]
I've added the deletion part which is the original insertion project with the new functions for deletion inserted.

**Comment by Alex-Cosma** [comment]
very well done

**Pull request merged**
