### PR TITLE
Assignement3+extra

### PR DESCRIPTION
**Pull request by andreeaonaciu**

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
Your code is nicely structured and written, no objections.
However, do you by any chance know or have worked with a @goiapaula ?

**Comment by goiapaula** [comment]
Umm nu stiu exact despre ce e vorba...dar eu nu cunosc nicio Andreea Onaciu.

**Comment by Alex-Cosma** [comment]
Oki doki, no worries about it ^^
you both did great.

**Comment by andreeaonaciu** [comment]
Thank you, as she said we didn't  work together and I don't know her either.

**Pull request merged**
