### PR TITLE
Open Adressing

### PR DESCRIPTION
**Pull request by birladeanuadrian**

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
@alungeipaula @birladeanuadrian 
You both chose the "team achiever" assignment, yet I only see the `open addressing` part. Am I missing anything?

**Comment by birladeanuadrian** [comment]
Eu am ales sa fac singur open adressing. V-am zis la sfarsitul orei.

2015-05-21 9:40 GMT+03:00 Cosma Alex notifications@github.com:

**Comment by alungeipaula** [comment]
I had to solve the assignment with Andreea Damsa, but,  as you can see,  we didn't send it. 

Trimis din Yahoo Mail pe Android

**Comment by Alex-Cosma** [comment]
Yes, I know, I'm sorry guys, I already deleted my comment - I've read the thing wrong

**Pull request merged**
