### PR TITLE
Radix Sort

### PR DESCRIPTION
**Pull request by alexh95**
Included radix sort in the existing sorting project.

### CODE REVIEW

**Comment by alexh95** [comment]
It may need some tweaks for incrementing the assignments variable(comparisons is set to 0 anyway). So far it seems to be 2 \* n \* noOfDigitsOfN(I only counted the two main loops, the number is probably larger)

**Comment by Alex-Cosma** [comment]
Great work

**Comment by Alex-Cosma** [comment]
And as a final thought at the end of the semester, you've done a great job overall. You've proven yourself to be an over-achiever; don't ever give this up!

**Comment by alexh95** [comment]
Hello,
I talked to a friend of mine and he would like to participate in the summer java course. He is a student at CTI - ro. AlexLecu is his git account.

**Comment by Alex-Cosma** [comment]
I've sent him an invitation. He can create a folder with his name himself and then commit/push/pull request so I can merge it on the main branch.

**Pull request merged**
