### PR TITLE
Assignment 2 - queue implementation

### PR DESCRIPTION
**Pull request by LacraDanciu**
Assignment 2 - queue

### CODE REVIEW

**Comment by LacraDanciu** [comment]
With assignments 2 I can't see where is the mistake. I tried Debug but nothing :(

**Comment by Alex-Cosma** [comment]
What exactly is the problem?

**Comment by LacraDanciu** [comment]
Assignment 2 - the one with doubly linked list. There I can't find the problem

**Comment by Alex-Cosma** [comment]
Take a look on how others implemented the `RemoveElementX` function. Steal a few ideas :+1:

**Comment by LacraDanciu** [comment]
Eventually that's what I'm going to do.

**Pull request merged**
