### PR TITLE
Queue(Auchan)

### PR DESCRIPTION
**Pull request by andras13**
I think it works but if there are any mistakes or efficiency problems please let me know. Thank you.

### CODE REVIEW

**Comment by andras13** [comment]
This is incredible... I tried out everything. Separately the functions work. But while debugging, doesn't outputs what outputs when I run the program without debug. Its very annoying!

**Comment by Alex-Cosma** [comment]
Weird indeed, I'll take a look at it a bit later

**Comment by Alex-Cosma** [comment]
Can you tell me exactly what's not working?

**Comment by andras13** [comment]
In the output the third and 4th rows are swapped. And I don't know why

**Comment by Alex-Cosma** [comment]
I didn't get the time to look at it, but it's not a biggie anyways

**Pull request merged**
