### PR TITLE
Third & Fourth Assignment

### PR DESCRIPTION
**Pull request by antalnorbert95**
Modified main so that the program is reading input from a file instead of having to type it in.

### CODE REVIEW

**Comment by antalnorbert95** [comment]
Updated as per feedback.

**Comment by Alex-Cosma** [comment]
Lovely work

**Comment by antalnorbert95** [comment]
Added fourth assignment to pull request.

**Comment by Alex-Cosma** [comment]
Damn you were quick! I will look over it this evening

**Comment by Alex-Cosma** [comment]
Awesomely done! Really really great
Keep it up!

**Pull request merged**
