### PR TITLE
Assignment 7

### PR DESCRIPTION
**Pull request by alexh95**
assignment7.1/Table with stats.odt contains statistics for the hash functions

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
Very well done, exactly what is needed.
Do the chaining one and you're done

**Comment by alexh95** [comment]
What would be a good standard deviation to indicate it is spread out efficiently?

**Comment by Alex-Cosma** [comment]
It depends on the number of elements in the buckets / the input size. The lower the better, of course

**Comment by alexh95** [comment]
Could not get it below 1, but it seems pretty well distributed.

**Comment by alexh95** [comment]
For the last function at least.

**Comment by Alex-Cosma** [comment]
What you should read about is 
http://en.m.wikipedia.org/wiki/68%E2%80%9395%E2%80%9399.7_rule
Now a low standard deviation is good but as I said it depends on the value of the things you are measuring. Think about this standard deviation as a "unit". A Gaussian distribution will follow this 68-95-99.7 rule which can be formulated like this:

Within 1 standard deviation of the average we can find 68 percent of all the observed values. 
Within 2 standard deviations of the average we can find 95 percent of all observed values. 
Within 3 standard deviations of the average we can find 99.7 percent of all observed values. 

In our case, let 'u' be the average number of elements per bucket. Let 'Xi' be the number of elements in bucket i and let 's' be the standard deviation. The rule would be

Pr(u-s < Xi < u+s) =~ 0.68
Pr(u-2s < Xi < u+2s) =~ 0.95
Pr(u-3s < Xi < u+3s) =~ 0.99

**Pull request merged**
