### PR TITLE
Finished assigment 1

### PR DESCRIPTION
**Pull request by alexh95**
I tried to make it look clean and to avoid using globals.

### CODE REVIEW

**Comment by alexh95** [comment]
The latest commit removes the useless return and the enum from io, and also the new reading method no longer has to compare the strings.
The whole for loop to determine whether to read a "%d" or not is replaced by:
    fgets()
    sscanf()

**Comment by Alex-Cosma** [comment]
It's quite alright. Check out the new "extra" assignment which I posted :+1:

**Comment by alexh95** [comment]
I've checked and the example in the extra is only valid if sentinels do not regenerate hp.

**Comment by Alex-Cosma** [comment]
Oh, snap! You are correct. I forgot about that.

I'll give an updated example in a few minutes which will take this case into consideration as well. Thank you

**Comment by Alex-Cosma** [comment]
Actually, forget about it. I just removed that requirement altogether. It was quite useless and didn't add any value to the problem. It made creating examples however quite a bit more difficult.

**Comment by alexh95** [comment]
Here is the extra assignment.
Though, is there a better way to read from the file an unknown number of ints without using fseek to roll back or processing the entire line?

**Comment by alexh95** [comment]
Thanks for the advice.
I'll try to revise the reading method and split that ugly battle function.
However is something like &((*Sentinel)->headArmy) supposed to work?

**Comment by Alex-Cosma** [comment]
Yea, I think it should work. does it not?

**Comment by Alex-Cosma** [comment]
Since you're already done with these 2 assignments (excluding the minor things to be modified on the last one) there are 2 things which you could do. 
- look in advance on the following lab topics (thought I'm thinking doubly linked / circular / sentinel lists won't really pose any challenge) and just "contemplate" on them, see if there's anything interesting or difficult and why not even experiment with them
- Take a look at what I posted a few days ago, the 'interesting stuff' things. Do the generic lists make sense to you, would you use something like that and if yes, you might even consider reimplementing your current assignments with generic lists. How about pointers to functions? Anything unclear there? 

I wouldn't want you to be 'out of work' so if you think you'd want a third assignment on lists, I could post the one which I'm going to give on doubly linked lists and you could start working on that. 
Either way, tell me whatever suits you fancy and we'll see to it.

**Comment by alexh95** [comment]
I finally completed the assignments using what you put in interesting stuff, the only thing I found too painfull to do is to list ALL the countries that could have defeated the sentinels on their own(in the way I would like it to be done), it only checks if the strongest country whould have one.

**Pull request merged**
