### PR TITLE
Read the comment in main.c first

### PR DESCRIPTION
**Pull request by birladeanuadrian**

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
I cannot accept your Kruskal implementation. It's way off / too complicated. 
The algorithm should be really straight forward! Rethink it - aerisește-l, e prea complicat făcut

**Comment by birladeanuadrian** [comment]
I am not sure. Have you received the new assignement?

**Comment by Alex-Cosma** [comment]
Yes I did

**Comment by Alex-Cosma** [comment]
Very good now

**Pull request merged**
