### PR TITLE
Revert "tema_nr1"

### PR DESCRIPTION
**Pull request by Alex-Cosma**
Reverts AC-2015-Sem2/DSA-lab#50

### CODE REVIEW

**Comment by bondocel11** [comment]
Thank you for your feedback. I have another question regarding the delete_first and delete_last functions.We take into consideration the one particular case where we have one element( if head==tail).The delete_first function only contains the " tail=NULL" statement,while in the delate_last we have " free(head); head==NULL ;tail==NULL" statements.Why is redundant to add "head==NULL" in the case of delete_first function.Also ,if we say that pointers head and tail will be null in the second statement,why do we have to add free(head).I guess I am failing to acknowledge the difference between these two functions when it comes to this particular case( of them having only one element).

**Comment by bondocel11** [comment]
Why is redundant to add "head==NULL" in the case of delete_first function?Also ,if we say that pointers head and tail will be null in the second statement,why do we have to add free(head)? sorry,these two were questions. I hope I explained well my issue

**Comment by Alex-Cosma** [comment]
Are you sure you want `head==NULL` instead of `head = NULL`?
Your delete first function is wrong by the way, can you tell me why?

**Comment by bondocel11** [comment]
I meant "head=NULL". It's wrong because I did not take into consideration the case where we have no elements in the list. Let me correct the message:

   I have another question regarding the delete_first and delete_last functions.We take into consideration the one particular case where we have one element( if head==tail).The delete_first function only contains the " tail=NULL" statement,while in the delate_last we have " free(head); head=NULL ;tail=NULL" statements.Why is redundant to add "head=NULL" in the case of delete_first function.Also ,if we say that pointers head and tail will be null in the second statement,why do we have to add free(head).I guess I am failing to acknowledge the difference between these two functions when it comes to this particular case( of them having only one element).  

 I was peeking in on the homework of other and I found this particular case of lists with one element( if (head==tail) and I did not understood neither its purpose,nor its different statements.:)
void    delete_first()
{
    t_list  *temp;

```
if (head == NULL)
    return ;
if (head == tail)
    tail = NULL;
temp = head;
head = head->next;
free(temp);
```

}

void    delete_last()
{
    t_list  *p;

```
if (head == NULL)
    return ;
if (head == tail)
{
    free(head);
    head = NULL;
    tail = NULL;
}
p = head;
while (p->next != tail)
    p = p->next;
p->next = NULL;
free(tail);
tail = p;
```

}

**Comment by Alex-Cosma** [comment]
You are perfectly right!
For the `head==tail` (them NOT being NULL), the code should be exactly the same in both functions. I might have overlooked this detail but the code should be:

```
    if(head==tail) {
        free(head); // or free(tail), it doesn't really matter.
        head=NULL;
        tail=NULL;
    }
```

You can actually read the question/top answers from [this post](http://stackoverflow.com/questions/1025589/setting-variable-to-null-after-free) if you are curious as to why exactly it isn't enough to simply have `free(head);` and having to write `head=NULL;` as well.

**Comment by bondocel11** [comment]
Imi pare rau am incercat sa uploadez tema cu modificari si cred ca am facut ceva prostii.O sa uploadez aici ca pare mai putin complicat.

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
typedef struct s_NODE
{
    int data;
    struct s_NODE _next;
} NODE;
NODE *head,_tail ;

void AF(int data) /_addFirst_/
{
    NODE _newnode;
    if (head==NULL)
    {
        head= (NODE_)malloc(sizeof(NODE));
        head->data=data;
        head->next=NULL;
        tail=head;
    }
    else
    {
        newnode=(NODE*)malloc(sizeof(NODE));
        newnode->data=data;
        newnode->next=head;
        head=newnode;
    }
}

void AL(int data) /_addLast_/
{
    NODE _newnode;
    if(head==NULL)
    {
        head=(NODE_)malloc(sizeof(NODE));
        head->data=data;
        head->next=NULL;
        tail=head;
    }
    else
    {
        newnode=(NODE_)malloc(sizeof(NODE));
        newnode->data=data;
        newnode->next=NULL;
        tail->next=newnode;
        tail=newnode;
    }
}
void DF()/_ delete first*/
{  if (head==NULL)
    return;
  if   (head==tail)
  {
      free(head);
      head=NULL;
      tail=NULL;
  }

```
NODE *tmp;
tmp=head;
head=head->next;
free(tmp);
```

   }

void DL()/_delete last_/
{
    if (head==NULL)
        printf("list is empty");
   if (head==tail)
   {
       free(tail);
       head=NULL;
       tail=NULL;
   }

```
    NODE *curr,*prev;
    curr=head;
    while (curr->next != NULL)
    {   prev=curr;
        curr=curr->next;
    }
    tail=prev;
    free(curr);

}
```

void DOOM_THE_LIST()/_deletes all_/
{
    NODE *temp;
    while (head != NULL)
    {
        temp = head;
        head = temp->next;
        free(temp);
    }
}

int DE(int x)
{
    NODE *temp, *prev;
    temp=head;
    while(temp!=NULL)
    {
        if(temp->data==x)
        {
            if(temp==head)
            {
                head=temp->next;
                free(temp);
                return 1;
            }
            else
            {
                prev->next=temp->next;
                free(temp);
                return 1;
            }
        }
        else
        {
            prev=temp;
            temp= temp->next;
        }
    }
    return 0;
}

void print_all(FILE *f2)
{
    NODE *p;
    p=head;
    while(p !=NULL)
    {
        fprintf(f2,"%d",p->data);
        p=p->next;
    }
    fprintf(f2,"\n");
}

void print_x(FILE *f2,int x)
{
    int cont;
    NODE *p;
    cont=0;
    p=head;
    while((p->next !=NULL)&&(cont<x))
    {
        fprintf(f2,"%d",p->data);
        p=p->next;
        cont++;
    }
    fprintf(f2,"\n");
}

void print_last_x(FILE *f2,int x)
{
    int     i;
    NODE    *curr;
    NODE    *start;

```
curr = head;
start = head;
i = 0;
while (curr != NULL)
{
    if (i >= x)
        start = start->next;
    curr= curr->next;
    ++i;
}
while (start != NULL)
{
    fprintf(f2, "%d ", start->data);
    start = start->next;
}
fprintf(f2, "\n");
```

}
int main()
{   FILE *f1;
    FILE *f2;
    char \* str;
    int data;
    f1=fopen("input.txt","r");
    f2=fopen("output.txt","w");

```
head=NULL;
tail=NULL;
```

   str=(char_)malloc(sizeof(char)_20);

```
while (fscanf(f1, "%s", str != EOF))
{
    fscanf(f1, "%d", &data);
    if (strcmp(str, "AF") == 0)
        AF(data);
    else if (strcmp(str, "AL") == 0)
        AL(data);
    else if (strcmp(str, "DF") == 0)
        DF();
    else if (strcmp(str, "DL") == 0)
        DL();
    else if (strcmp(str, "DOOM_THE_LIST") == 0)
        DOOM_THE_LIST();
    else if (strcmp(str, "DE") == 0)
        DE(data);
    else if (strcmp(str, "PRINT_ALL") == 0)
        print_all(f2);
    else if (strcmp(str, "PRINT_F") == 0)
        print_x(f2, data);
    else if (strcmp(str, "PRINT_L") == 0)
        print_last_x(f2, data);
}
fclose(f1);
fclose(f2);
return (0);
```

}

--problema e ca nu imi printeaza nimic in output.

**Comment by bondocel11** [comment]
I tryed to upload my modified version of the first assignment but I messed everything up.I'll upload it here,as it is safer. I still have some issues as it would not print anything in output.txt.Also,I have 2 warnings that I can't fix.

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
typedef struct s_NODE
{
    int data;
    struct s_NODE _next;
} NODE;
NODE *head,_tail ;

void AF(int data) /_addFirst_/
{
    NODE _newnode;
    if (head==NULL)
    {
        head= (NODE_)malloc(sizeof(NODE));
        head->data=data;
        head->next=NULL;
        tail=head;
    }
    else
    {
        newnode=(NODE*)malloc(sizeof(NODE));
        newnode->data=data;
        newnode->next=head;
        head=newnode;
    }
}

void AL(int data) /_addLast_/
{
    NODE _newnode;
    if(head==NULL)
    {
        head=(NODE_)malloc(sizeof(NODE));
        head->data=data;
        head->next=NULL;
        tail=head;
    }
    else
    {
        newnode=(NODE_)malloc(sizeof(NODE));
        newnode->data=data;
        newnode->next=NULL;
        tail->next=newnode;
        tail=newnode;
    }
}
void DF()/_ delete first*/
{  if (head==NULL)
    return;
  if   (head==tail)
  {
      free(head);
      head=NULL;
      tail=NULL;
  }

```
NODE *tmp;
tmp=head;
head=head->next;
free(tmp);
```

   }

void DL()/_delete last_/
{
    if (head==NULL)
        printf("list is empty");
   if (head==tail)
   {
       free(tail);
       head=NULL;
       tail=NULL;
   }

```
    NODE *curr,*prev;
    curr=head;
    while (curr->next != NULL)
    {   prev=curr;
        curr=curr->next;
    }
    tail=prev;
    free(curr);

}
```

void DOOM_THE_LIST()/_deletes all_/
{
    NODE *temp;
    while (head != NULL)
    {
        temp = head;
        head = temp->next;
        free(temp);
    }
}

int DE(int x)
{
    NODE *temp, *prev;
    temp=head;
    while(temp!=NULL)
    {
        if(temp->data==x)
        {
            if(temp==head)
            {
                head=temp->next;
                free(temp);
                return 1;
            }
            else
            {
                prev->next=temp->next;
                free(temp);
                return 1;
            }
        }
        else
        {
            prev=temp;
            temp= temp->next;
        }
    }
    return 0;
}

void print_all(FILE *f2)
{
    NODE *p;
    p=head;
    while(p !=NULL)
    {
        fprintf(f2,"%d",p->data);
        p=p->next;
    }
    fprintf(f2,"\n");
}

void print_x(FILE *f2,int x)
{
    int cont;
    NODE *p;
    cont=0;
    p=head;
    while((p->next !=NULL)&&(cont<x))
    {
        fprintf(f2,"%d",p->data);
        p=p->next;
        cont++;
    }
    fprintf(f2,"\n");
}

void print_last_x(FILE *f2,int x)
{
    int     i;
    NODE    *curr;
    NODE    *start;

```
curr = head;
start = head;
i = 0;
while (curr != NULL)
{
    if (i >= x)
        start = start->next;
    curr= curr->next;
    ++i;
}
while (start != NULL)
{
    fprintf(f2, "%d ", start->data);
    start = start->next;
}
fprintf(f2, "\n");
```

}
int main()
{   FILE *f1;
    FILE *f2;
    char \* str;
    int data;
    f1=fopen("input.txt","r");
    f2=fopen("output.txt","w");

```
head=NULL;
tail=NULL;
```

   str=(char_)malloc(sizeof(char)_20);

```
while (fscanf(f1, "%s", str != EOF))
{
    fscanf(f1, "%d", &data);
    if (strcmp(str, "AF") == 0)
        AF(data);
    else if (strcmp(str, "AL") == 0)
        AL(data);
    else if (strcmp(str, "DF") == 0)
        DF();
    else if (strcmp(str, "DL") == 0)
        DL();
    else if (strcmp(str, "DOOM_THE_LIST") == 0)
        DOOM_THE_LIST();
    else if (strcmp(str, "DE") == 0)
        DE(data);
    else if (strcmp(str, "PRINT_ALL") == 0)
        print_all(f2);
    else if (strcmp(str, "PRINT_F") == 0)
        print_x(f2, data);
    else if (strcmp(str, "PRINT_L") == 0)
        print_last_x(f2, data);
}
fclose(f1);
fclose(f2);
return (0);
```

}

**Comment by bondocel11** [comment]
Now I see it's not printed as it should be.What do I do?

**Comment by Alex-Cosma** [comment]
I'd rather fix your git first so you could work 'normally'

**Pull request merged**
