### PR TITLE
Homework

### PR DESCRIPTION
**Pull request by DaianaSpataceann**
I don't know why I put twice the folder with the homework.

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
I have no idea why you have a function copied inside your main method and at this point I'm too afraid to ask

**Comment by Alex-Cosma** [comment]
But nevertheless, your program doesn't run correctly..

**Comment by DaianaSpataceann** [comment]
Ups I sent the wrong code....i did not verify what i put on git.

**Comment by Alex-Cosma** [comment]
You could commit/push again and create a new pull request

**Pull request merged**
