### PR TITLE
Assignment 4

### PR DESCRIPTION
**Pull request by vladms**
I hope it is okay.

### CODE REVIEW

**Comment by vladms** [comment]
I have a problem with the heights of some nodes..I will upload a better solution.

**Comment by Alex-Cosma** [comment]
Please put the whole project on git (including the `.cbp` file)

**Comment by Alex-Cosma** [comment]
You deleted all the files :))

**Comment by vladms** [comment]
I hope now it is fine in either of them

**Comment by Alex-Cosma** [comment]
Almost. There is no "main" file

**Comment by vladms** [comment]
Now it is okay? I have big problems with conflicts

**Comment by Alex-Cosma** [comment]
It's fine now, good work

**Pull request merged**
