### PR TITLE
Hash Tables

### PR DESCRIPTION
**Pull request by Ranapop**
I have worked a bit on the code for the hash Table with chaining... it is not done yet.... i don't know if I have done the functions well, for both buckets distribution and standard deviation.... especially standard deviation.... i analysed some formula from that wikipedia page and I implemented it... i do hope I've chosen that wisely. So that is why I haven't filled up the table yet. 
As for the other part of the assignment, implementing hash tables with open addressing, I am afraid I won't be able to do it. I have been working on it for quite some time now.... but for some reason I haven't yet identified, it (don't know the word in english), it "crapa".
Please give me a feedback on this code as soon as possible so I can at least complete this part of the assignment and than move back to the other one.

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
Everything else looks fine

**Comment by Ranapop** [comment]
Great! I'll fix that and try to do the other one as well! Thank you!

**Comment by Alex-Cosma** [comment]
Swell job this semester - over-achieving and all that, don't ever give up on it

**Comment by Ranapop** [comment]
Thx!

**Comment by Ranapop** [comment]
Oh! It really means a lot to me getting such a positive feedback. Thank you... a looot :)

**Pull request merged**
