### PR TITLE
Assignment 2.1

### PR DESCRIPTION
**Pull request by gergo-papp**
Assignments 2.1 & 2.2

Sorry for those extra commits. I was "experimenting".

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
I just corrected your test.
if you would have written
`void Append(NodeT **aRef, NodeT **bRef)` instead of `void Append(struct Node **aRef, struct node **bRef)` you would not have had warnings. Be just a bit more careful in the future.

Good job nevertheless

**Comment by gergo-papp** [comment]
I know. But you sad at least twice, that we cannot change the function's header. So I left is so, because it was an error not a warning. Good afternoon, Gergő Gesendet von Yahoo Mail für iPhoneUm 17.03.2015 4:26:29 nachm. schrieb Cosma Alex:I just corrected your test.
if you would have written
void Append(NodeT *_aRef, NodeT *_bRef) instead of void Append(struct Node *_aRef, struct node *_bRef) you would not have had warnings. Be just a bit more careful in the future.

**Comment by Alex-Cosma** [comment]
You are right, however I was referring to the types / numbers of pointers there.
Oh forget about it, I won't tax you for this :+1:

**Comment by gergo-papp** [comment]
Thank you!Gesendet von Yahoo Mail für iPhoneUm 17.03.2015 4:51:26 nachm. schrieb Cosma Alex:You are right, however I was referring to the types / numbers of pointers there.
Oh forget about it, I won't tax you for this

**Comment by Alex-Cosma** [comment]
Don't mention it ^^

**Pull request merged**
