### PR TITLE
This is my first version of assignment5.1

### PR DESCRIPTION
**Pull request by Ranapop**
Here is the first version of assignment 5.1.
As you can see, i've worked directly on the code from the laboratory, I hope that's alright.
I am not sure about whether I have approached the problem well. I do not know if that is the correct way of implementing adjacency lists, please tell me if I should have done it differently, and how.

### CODE REVIEW

**Comment by Alex-Cosma** [comment]
`As you can see, i've worked directly on the code from the laboratory, I hope that's alright.`
Of course it's alright

**Comment by Alex-Cosma** [comment]
Your code looks fine, good work!

**Comment by Ranapop** [comment]
Thank you :). If all is well, I'll move on to the other assignment.

**Comment by Alex-Cosma** [comment]
Yes, this would be half the solution however you still have to print the path

**Pull request merged**
